[profile.default]
src = "contracts"
out = "forge-out"
libs = ["node_modules"]
test = "test/foundry"
cache_path = "forge-cache"

# Solidity compiler settings
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = false

# Fuzz testing configuration
fuzz_runs = 256
fuzz_max_test_rejects = 65536

# Invariant testing configuration
invariant_runs = 256
invariant_depth = 15

# Additional settings
verbosity = 2
gas_reports = ["CAPToken"]
gas_reports_ignore = []

# RPC endpoints (uses .env)
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# Formatting
[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
